.dashBibtex_js_metadata <- function() {
deps_metadata <- list(`dash_bibtex` = structure(list(name = "dash_bibtex",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-DashBibtex.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashBibtex",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_bibtex` = structure(list(name = "dash_bibtex",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-DashBibtex.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashBibtex",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_bibtex` = structure(list(name = "dash_bibtex",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_bibtex.min.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashBibtex",
all_files = FALSE), class = "html_dependency"),
`dash_bibtex` = structure(list(name = "dash_bibtex",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_bibtex.min.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashBibtex",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"))
return(deps_metadata)
}
